WIP: tasty-plutus: Add outputsToInputs (#62)
Liqwid-Labs/plutus-extra pull request #101
Opened 2021-11-26 03:48 UTC by sergesku

As a solution to Issue #62, we can provide the function:
```
outputsToInputs :: ContextBuilder p -> [Input]
outputsToInputs (ContextBuilder _ outs _ _ _) =
  toList $ fmap (\(Output t v) -> Input t v) outs
```
Usage examples:
```
nextInputs <- outputsToInputs validContext <$ shouldValidateProducing "Valid case" validData validContext
do something with nextInputs
```
```
shouldValidateProducing "Valid case" validData validContext
let nextInputs = outputsToInputs validContext
do something with nextInputs
```
```
nextInputs <- liftA2 (<$) outputsToInputs (shouldValidateProducing "Valid case" validData) validContext
do something with nextInputs
```

2021-11-28 18:14 UTC, kozross requested changes

2021-11-28 18:14 UTC, kozross commented on tasty-plutus/CHANGELOG.md
> +## 4.1.1 -- 2021-11-26
This should be 4.2 - we use only two version numbers.

2021-11-28 18:14 UTC, kozross commented on tasty-plutus/src/Test/Tasty/Plutus/Internal/Context.hs
> + @since 4.1.1
Likewise here, this should be 4.2.

2021-11-29 21:47 UTC, blamario commented
The example line

    nextInputs <- outputsToInputs validContext <$ shouldValidateProducing "Valid case" validData validContext

is using the function `shouldValidateProducing` which I understand is not supposed to exist in this PR. I presume that was meant to be `shouldValidate` instead. This line is equivalent to the next example's corrected

    shouldValidate "Valid case" validData validContext
    let nextInputs = outputsToInputs validContext

The problem with this logic is that it only works if `validContext` specifies the exact output UTxOs. In one use case I had in mind for this functionality, it can't do that because one of the outputs is freshly minted. I was assuming that `shouldValidateProducing`  would return the actual UTxOs produced by the script, not those specified by the context. Is that impossible?

2021-11-29 22:23 UTC, sergesku commented
I fixed examples in description.

2021-12-01 00:44 UTC, sergesku commented
Validation of the script does not create any additional outputs that are not specified in the ScriptContext. Therefore, all we can do is use the context outputs as inputs for the new context.

2021-12-01 18:07 UTC, kozross approved these changes

2021-12-01 18:07 UTC, merged