Datums and UTXOs handling functions
Liqwid-Labs/plutus-extra pull request #15
Opened 2021-09-17 22:03 UTC by prutz1311

2021-09-18 00:41 UTC, kozross requested changes
We need a minor version bump and a CHANGELOG entry as well.

2021-09-18 00:41 UTC, kozross commented on plutus-extra/src/Plutus/V1/Ledger/Contexts/Extra.hs
> +{- | Helper function to parse a UTXO's datum and keep the UTXO
This requires an `@since`, as per the [style guide](https://github.com/mlabs-haskell/styleguide#documentation).

2021-09-18 00:41 UTC, kozross commented on plutus-extra/src/Plutus/V1/Ledger/Contexts/Extra.hs
> +getAllOutputsWithDatum ::
As does this.

2021-09-18 00:41 UTC, kozross commented on plutus-extra/src/Plutus/V1/Ledger/Contexts/Extra.hs
> +getScriptOutputsWithDatum ::
And this.

2021-09-22 19:30 UTC, kozross commented
@prutz1311 - could you rebase this against current `master`? There seem to have been some Nix changes blocking this from building properly.

2021-09-23 02:08 UTC, prutz1311 commented
@kozross This PR was already based on 8d6f921069e93853284920d39e539ecc15bf2cde , the current HEAD commit

2021-09-23 23:32 UTC, merged